# docker-compose.yml
version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-master  # Nom personnalisé de l'image
    container_name: geostudio_postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - geostudio-postgis:/var/lib/postgresql/data  # Nom du volume personnalisé
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  imposm:
    build:
      context: ./imposm
      args:
        PBF_URLS: ${PBF_FILES}
    container_name: geostudio_imposm
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - PBF_URLS=${PBF_FILES}
      - PGHOST=postgis
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    volumes:
      - geostudio-imposm:/data  # Nom du volume personnalisé

volumes:
  geostudio-postgis:  # Définition des volumes
  geostudio-imposm:
